Fix flickering test and simplify generate data for limit tests
The test for routes sometimes fails:

Test stderr: Traceback (most recent call last):
  File "test.py", line 44, in <module>
    run_test()
  File "test.py", line 40, in run_test
    assert routes[-1] in paths, f"Route {routes[-1]} should be in reported paths"
AssertionError: Route /3xy2copptle/yll-/265/n89sadn_8/5_o4h_zw26a8f/v_a0nkuahmr/izduz19nbza9le/ydk2-yr3m/odbm77xj/zgw5u5azbkh7/-qz9/3w6mdkwx267/kgw/xd-s1/ahsdzingurr/l9-84_o/gd2wrtobgp/ljjo0iip3h/g4sfuocfg45dg should be in reported paths

It's because a route segment might contain enough entropy to be seen as
a secret. So the segment would be replaced by :secret, thus the original
route wouldn't be in the reported routes.

Let's improve the other tests too.